Patch default cache when using the cache panel
jazzband/django-debug-toolbar pull request #1437
Opened 2021-01-20 17:12 UTC by gilmrjc

The test for the cache panel are broken on master (ea65261). The problem is caused for a change in how Django handles the default cache connection on version 3.2. This PR handles the new connection system to avoid this problem.

2021-01-20 17:26 UTC, gilmrjc commented
There is a problem with Codecov uploads from the sqlite branch, which is the one testing the integration with the Django master branch. Taken that into account there is no coverage loss with the proposed changes.

2021-01-20 19:16 UTC, auvipy approved these changes

2021-01-20 19:42 UTC, tim-schilling requested changes
It doesn't appear to be necessary to import `ConnectionProxy`. I was able to get the tests to pass with:

    cache.cache = cache.caches[DEFAULT_CACHE_ALIAS]

Thanks for pointing out the simpler solution than I was working on.

2021-01-20 21:33 UTC, gilmrjc commented
> It doesn't appear to be necessary to import `ConnectionProxy`. I was able to get the tests to pass with:
> 
> ```
> cache.cache = cache.caches[DEFAULT_CACHE_ALIAS]
> ```
> 
> Thanks for pointing out the simpler solution than I was working on.

I used the `ConnectionProxy` because that's the new class used in the Django codebase. It's possible to only change the default cache without creating a new instance of `ConnectionProxy` but maybe it can cause problems somewhere else. I haven't tested a large application with this so I'm not sure.

2021-01-20 22:42 UTC, tim-schilling commented
Ah, that's why I was patching the existing connections in #1427

2021-01-20 23:22 UTC, gilmrjc commented
The difference with #1427 is the patched class there is `CacheHandler` but now the default cache is initialized with the new `ConnectionProxy` class.

In Django 3.1 and below the default proxy created the connection on access time with `CacheHandler`, including the default cache connection. If the patch was applied before any call the connection would be instrumented.

With the new logic (https://github.com/django/django/blob/7b3ec6bcc8309d5b2003d355fe6f78af89cfeb52/django/core/cache/__init__.py#L49) the default cache is instantiated on load time and when the patch to `CacheHandler` is applied the connection is already encapsulated in a `ConnectionProxy` object.

This is why the old patch can't instrument the default cache but it works when accessing `cache.caches["default"]` or other caches, because `cache.caches["default"]` and `cache.cache` are two different objects, where in Django 3.1 and below they were the same.

2021-01-21 23:18 UTC, tim-schilling commented
Sounds good, but can we work the inline import out of the code? One option would be to create our own version of `ConnectionProxy` in a `compat.py` file, then import the compat version when the Django version is less than 3.1.

2021-01-22 00:42 UTC, gilmrjc commented
Can I ask why you want to avoid the import? It's actually used to detect if the new patch is needed:

```python
try:
    from django.utils.connection import ConnectionProxy

    cache.cache = ConnectionProxy(cache.caches, DEFAULT_CACHE_ALIAS)
except ImportError:
    pass
```

If `ConnectionProxy` is not found it means we are on Django 3.1 or below and nothing happens. If the class is imported then the patch to `cache.cache` is needed. This is a idiomatic way to detect  API changes in Python when dealing with multiple versions of a dependency.

I'm open to change it to `compat.py`, just want to understand the logic behind the suggestion.

2021-01-22 03:53 UTC, tim-schilling commented
The reason for the suggestion is to get the import statement to the top of the file rather than having it inline. It's not about the actual try/except flow.

2021-01-22 15:49 UTC, gilmrjc commented
Ok, the import is now at the top. It is a minor change and it's still just patching when needed 😄

2021-01-23 17:14 UTC, matthiask approved these changes
I think we should move ahead with this. I have suggested two small-ish changes so that we do not have to use the broad `try ... except NameError` clause.

2021-01-23 17:14 UTC, matthiask commented on debug_toolbar/panels/cache.py
> +    pass
```suggestion
    ConnectionProxy = None
```

2021-01-23 17:14 UTC, matthiask commented on debug_toolbar/panels/cache.py
> +            pass
```suggestion
        # Wrap the patched cache inside Django's ConnectionProxy
        if ConnectionProxy:
            cache.cache = ConnectionProxy(cache.caches, DEFAULT_CACHE_ALIAS)
```

2021-01-23 17:17 UTC, tim-schilling approved these changes

2021-01-23 17:18 UTC, merged